homeassistant:
  name: Home
  latitude: !env_var HASS_LATITUDE
  longitude: !env_var HASS_LONGITUDE
  elevation: !env_var HASS_ELEVATION
  packages: !include_dir_named integrations
  allowlist_external_dirs: !include whitelist_external_dirs.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)

default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/16
    - 192.168.0.0/16
#sensor:
#  - platform: dte_energy_bridge
#    ip: 192.168.10.131
#    version: 2
#    name: DTE Energy Brige

sensor:
###############################
## DTE Energy Bridge         ##
  - platform: mqtt 
    name: "DTE Instantaneous Demand" 
    state_topic: "event/metering/instantaneous_demand" 
    unit_of_measurement: 'W' 
    value_template: "{{ value_json.demand | round(0) }}"

  - platform: mqtt
    name: "DTE Energy Bridge Summary"
    state_topic: "event/metering/summation/minute"
    unit_of_measurement: 'W'
    value_template: "{{ value_json.value | round(0) }}" 

  - platform: integration
    source: sensor.dte_energy_bridge_summary
    name: energy_spent
    unit_prefix: k
    round: 2
#####################################


#################
# UTILITY METER # 
#################
utility_meter:
  energy_daily:
    source: sensor.energy_spent
    cycle: daily
    tariffs:
      - standard

opnsense:
  url: !env_var SECRET_OPNSENSE_URL
  api_secret: !env_var SECRET_OPNSENSE_SECRET
  api_key: !env_var SECRET_OPNSENSE_KEY


recorder:

  # The URL that points to your database.
  db_url: !env_var SECRET_RECORDER_DB_URL

  # The number of days of history to keep in the recorder database
  purge_keep_days: 32

  # Exclude the following items from recordings
  exclude:
    # The list of entity ids to be excluded from recordings.
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.time
      - sensor.time_utc

#######################
##  Hubitat Devices  ##
#######################


# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

